dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "6"
cache:
  yarn: true
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
before_script:
  - truffle version
  - yarn list
script:
  - yarn test
